config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friends
  resources :orders
  resources :groups
  resources :groups_users

  root to: "home#index"

  
  get '/friends/:id/accept', to: 'friends#accept'
  get '/friends/:id/decline', to: 'friends#decline'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get "/orders", to: "orders#index"
  get '/orders/new', to: 'orders#new'
  post '/orders', to: 'orders#create', as: 'newOrder'
  get '/orders/:id/show', to: 'orders#show', as: 'viewOrder'
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'cancelOrder'
  get '/orders/:id/finish', to: 'orders#finish', as: 'finishOrder'

  get '/orders/invite/:id' => 'orders#inviteFriends', as: 'inviteFriends'
  post '/orders/invite/:id' => 'orders#invite', as: 'invite'
  post '/orders/inviteGroup/:id' => 'orders#inviteGroup', as: 'inviteGroup'
  delete '/orders/invite/:id' => 'orders#cancelInvitation', as: 'cancel'

  get '/orders/:id/items/new', to: 'items#new'
   
  post '/orders/:id/', to: 'items#create', as: 'newItem'
  get '/orders/:id/items/:item_id/delete', to: 'items#delete',as: 'deleteItem'

end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence:true, uniqueness:true
  has_and_belongs_to_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.where(creator: current_user.id)
  end
  def show
    @groups = Group.where(creator: current_user.id)
    @group = Group.find_by(id: params[:id], creator: current_user.id)
    if @group.nil?
      flash[:group_error] = "This id is not matching with any Friends "
      redirect_to :groups
    else
      @group_members = @group.users.all
    end
    
  end

  def create
    @group = Group.new
    @group.creator = current_user.id
    @group.name = params[:name]
    @group.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @group = Group.find params[:id]
    if @group.destroy
      flash[:delete_notice] = "You have successfully deleted your group"
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <%= form_tag groups_path do |form| %>
        <div class="active-purple-4 mb-4 d-flex">
          <%= text_field_tag(:name, nil, placeholder: "Group name", class: "form-control mx-2") %>
          <%= submit_tag "Create", class: "btn btn-dark" %>
        </div>

      <% end %>
    </div>
    <div class="col-12 col-md-5 col-lg-5 mt-5">
      <table class="table table-dark">
        <thead>
    <tr>
    <td colspan="2">My Groups</td>
    </tr>
  </thead>

        <!-- Show error msgs -->
    <% if flash[:group_errors]%>
        <div class="alert alert-danger">
            <% flash[:group_errors].each do |msg|%>
            <li>
                <%= msg %>
            </li>
            <% end %>
        </div>
    <% end %>
    <% if flash[:group_error]%>
        <div class="alert alert-danger">
            <li>
                <%= flash[:group_error] %>
            </li>
        </div>
    <% end %>
        <% unless @groups.nil? %>
            <tbody>
            <% @groups.each do |group| %>
              <tr>
                <td><%= group.name %></td>
                <td><%= link_to 'Edit Group', group_path(group), class: "btn btn-primary" %></td>
                <td><%= link_to 'Delete Group', group_path(group), class: "btn btn-primary", method: :delete,
                                data: {confirm: 'Are you sure?'} %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>

      </div>
    </div>

  </div>
</div>

app/views/groups/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <%= form_tag groups_path do |form| %>
        <div class="active-purple-4 mb-4 d-flex">
          <%= text_field_tag(:name, nil, placeholder: "Group name", class: "form-control mx-2") %>
          <%= submit_tag "Create", class: "btn btn-dark" %>
        </div>

      <% end %>
    </div>
    <div class="col-12 col-md-5 col-lg-5 mt-5">
      <table class="table table-dark">
        <thead>
        <tr>
          <td colspan="2">My Groups</td>
        </tr>
        </thead>

        <!-- Show error msgs -->
        <% if flash[:group_errors] %>
          <div class="alert alert-danger">
            <% flash[:group_errors].each do |msg| %>
              <li>
                <%= msg %>
              </li>
            <% end %>
          </div>
        <% end %>
        <% if flash[:group_error] %>
          <div class="alert alert-danger">
            <li>
              <%= flash[:group_error] %>
            </li>
          </div>
        <% end %>
        <% unless @groups.nil? %>
            <tbody>
            <% @groups.each do |group| %>
              <tr>
                <td><%= group.name %></td>
                <%= form_tag  group_path(group), method: "get" do |form| %>
                <td><%= submit_tag 'Edit Group',   class: "btn btn-primary" %></td>
                <% end %>
                <td><%= link_to 'Delete Group', group_path(group), class: "btn btn-primary", method: :delete,
                                data: {confirm: 'Are you sure?'} %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>

        </div>
  </div>

  <!-- Show group and its members-->

  <div class="col-12 col-md-7 col-lg-7 mt-5">
    <table class="table table-dark">
      <thead>
      <tr>
        <td colspan="2"><%= @group.name %></td>
      </tr>
      </thead>
      <% if flash[:group_member_errors] %>
        <div class="alert alert-danger">
          <% flash[:group_member_errors].each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </div>
      <% end %>
      <%= form_tag groups_users_path do |form| %>
        <div class="active-purple-4 mb-4 d-flex">
          <%= hidden_field_tag(:group_id, @group.id) %>
          <%= label_tag(:email, "Add friend", style: "margin-right:10px") %>
          <%= email_field_tag(:email, nil, class: "form-control") %>
          <%= submit_tag("Add", class: "btn btn-dark", style: "margin-left:30px") %>
        </div>

      <% end %>
      <% @group_members.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= link_to 'Delete', groups_user_path(group_id: @group, user_id: user), class: "btn btn-primary", method: :delete,
                          groups: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>