config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friends
  resources :orders
  resources :groups
  resources :groups_users

  root to: "home#index"

  
  get '/friends/:id/accept', to: 'friends#accept'
  get '/friends/:id/decline', to: 'friends#decline'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get "/orders", to: "orders#index"
  get '/orders/new', to: 'orders#new'
  post '/orders', to: 'orders#create', as: 'newOrder'
  get '/orders/:id/show', to: 'orders#show', as: 'viewOrder'
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'cancelOrder'
  get '/orders/:id/finish', to: 'orders#finish', as: 'finishOrder'

  get '/orders/invite/:id' => 'orders#inviteFriends', as: 'inviteFriends'
  post '/orders/invite/:id' => 'orders#invite', as: 'invite'
  post '/orders/inviteGroup/:id' => 'orders#inviteGroup', as: 'inviteGroup'
  delete '/orders/invite/:id' => 'orders#cancelInvitation', as: 'cancel'

  get '/orders/:id/items/new', to: 'items#new'
   
  post '/orders/:id/', to: 'items#create', as: 'newItem'
  get '/orders/:id/items/:item_id/delete', to: 'items#delete',as: 'deleteItem'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :items

  enum meal_type: [ :Breakfast, :Lunch, :Dinner ]
  enum order_status: [ :Waiting, :Finished, :Cancelled ]

  has_one_attached :restaurant_menu

  validates :meal_type, presence: true
  validates :restaurant_name, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id, order_status: 0)
    @invites = Invitation.where(user_id: current_user.id)
    @orders_from_invitations = []
    @invites.each do |invite|
      order = Order.find_by(id: invite.order_id, order_status: 0)
      if order
        @orders_from_invitations.append(order)
      end
    end

    @orders.each do |order|
      @orders_from_invitations.append(order)
    end
  end

  def new
    @order = Order.new
  end

  def show
    @order = Order.where(id: params[:id]).first
    @items = Item.where(order: params[:id])
  end

  def create
    @order_params = params.require(:newOrder).permit(:meal_type, :restaurant_name, :restaurant_menu)
    @order = Order.new(@order_params)
    @order.order_status = 0
    @order.user_id = current_user.id
    if @order.save
      @invites = Invitation.where(user_id: current_user.id)
      @orders = Order.where(user_id: current_user.id, order_status: 0)
      render 'index'
    else
      render 'new'
    end
  end

  def cancel
    @order_id = params[:id]
    @order = Order.find(id = @order_id)
    if @order.user_id == current_user.id
      @order.order_status = 2
      @order.save
      redirect_to orders_path
    else
      redirect_to orders_path
    end
  end

  def finish
    @order_id = params[:id]
    @order = Order.find(id = @order_id)
    if @order.user_id == current_user.id
      @order.order_status = 1
      @order.save
      redirect_to orders_path
    else
      redirect_to orders_path
    end
  end

  def inviteFriends
    @friends_arr = []
    current_user.friendships.each do |friendship|
      @friendsToInvite = @friends_arr.push(User.find(id = friendship.friend_id))
    end

    @groups = Group.where(creator: current_user.id)
    @invited_arr = []
    @order = Order.find(id = params['id'])
    @invite = Invitation.where(order_id: @order.id)
    @invite.each do |invitation|
      @invitedFriends = @invited_arr.push(User.find(id = invitation.user_id))
    end

    @joined_arr = []
    @joined = Invitation.where(order_id: @order.id, joined: true)
    @joined.each do |invitation|
      @joinedFriends = @joined_arr.push(User.find(id = invitation.user_id))
    end
  end

  def cancelInvitation
    @cancel_id = params["cancel-btn"]
    @order = Order.find(id = params['id'])
    @invite = Invitation.where(order_id: @order.id)
    p 'cancel id ====', @cancel_id
    if not @cancel_id.nil?
      p params
      @deleted_invitation = @invite.where(user_id: @cancel_id)
      @deleted_invitation.delete_all
    end
    redirect_to inviteFriends_path
  end

  def invite
    @friend_id = params['invite-btn']
    @friend = User.find(id = @friend_id)
    @order = Order.find(id = params['id'])

    if Invitation.where(user_id: @friend.id, order_id: @order.id).present?
      flash[:danger] = "#{@friend.first_name} is already invited"
      redirect_to inviteFriends_path
    elsif @new_invite = Invitation.new()
      @new_invite.user = @friend
      @new_invite.order = @order
      @new_invite.save
      redirect_to inviteFriends_path
    end
  end

  def inviteGroup
    @group_id = params["inviteGroup-btn"]
    @order = Order.find(id = params['id'])
    @groupToInvite = Group.find_by(id: @group_id)
    @groupToInvite_members = @groupToInvite.users.all

    @groupToInvite_members.each do |user|
      if Invitation.where(user_id: user.id, order_id: @order.id).present?
        flash[:danger] = "#{user.first_name} is already invited"
      elsif @new_invite = Invitation.new()
        @new_invite.user = user
        @new_invite.order = @order
        @new_invite.save
      end
    end
    redirect_to inviteFriends_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="mt-0">
  <h1 class="text-center fw-bold"> Orders </h1>
</div>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">User</th>
      <th scope="col">Meal</th>
      <th scope="col">Restaurant</th>
      <th scope="col">Joined</th>
      <th scope="col">Invited</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <% @orders.each do |order| %>
  <tr>
    <td><a href="/orders/<%=order.id%>"><%= order.user_id %></a></td>
    <td><a href="/orders/<%=order.id%>"><%= order.meal_type %></a></td>
    <td><a href="/orders/<%=order.id%>"><%= order.restaurant_name %></a></td>
    <td><%= @invites.count {|invite| invite.order_id == order.id } %></td>
    <td><%= @invites.count {|invite| (invite.order_id == order.id && invite.joined == true)} %></td>
    <td><%= order.order_status %></td>
    <td><%= link_to "View", viewOrder_path(order) , class: "btn btn-info btn-sm", method: :get %></td>
    <td><%= link_to "Finish", finishOrder_path(order) , class: "btn btn-success btn-sm", method: :get %></td>
    <td><%= link_to "Cancel", cancelOrder_path(order) , class: "btn btn-danger btn-sm", method: :get %></td>
  </tr>
  <%end%>
  </thead>
</table>

<div class="col-md-4" style="margin: 10px;">
  <%= link_to "Start New Order", "/orders/new" , class: "btn btn-primary"%>
</div>

app/views/orders/inviteFriends.html.erb
<h1>Invite friends to Your order</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Your Friends</b>
        </div>
        <div class="card-body">

          <%= form_for :invite, url: invite_url do |f| %>
            <% flash.each do |type, msg| %>
              <div class="alert alert-<%= type %> ">
                <%= msg %>
              </div>
            <% end %>
            <% unless @friendsToInvite.nil? %>
              <% @friendsToInvite.each do |friend| %>
                <div>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= "#{friend.first_name}  #{friend.last_name}" %>
                    </h5>
                    <p><%= friend.email %></p>

                    <%= f.button "Invite", action_name: 'orders#invite', name: "invite-btn", value: friend.id, class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="text-center col-12">You have no friends yet.</h4>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Your groups</b>
        </div>
        <div class="card-body">
          <%= form_for :inviteGroup, url: inviteGroup_url do |f| %>
          <% flash.each do |type, msg| %>
              <div class="alert alert-<%= type %> ">
                <%= msg %>
              </div>
            <% end %>
              <% unless @groups == [] %>
                  <% @groups.each do |group| %>                
                      <div>
                          <div class="card-body">
                              <h5 class="card-title"><%= group.name %></h5>                    
                              <% group.users.all.each do |user| %>
                                  <p>
                                  <h6><%= "#{user.first_name}  #{user.last_name}" %></h6>
                                  </p>
                              <% end %>
                              <%= f.button 'Invite Group', action_name: 'orders#inviteGroup', name: "inviteGroup-btn", value: group.id, class: "btn btn-primary" %>
                          </div>
                      </div>
                  <% end %>
              <% else %>
                  <h4 class="text-center col-12">You have no groups</h4>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Invited friends</b>
        </div>
        <div class="card-body">

          <%= form_for :cancel, url: cancel_path, method: :delete do |f| %>
            <% unless @invitedFriends.nil? %>
              <% @invitedFriends.each do |friend| %>
                <div>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= "#{friend.first_name}  #{friend.last_name}" %>
                    </h5>
                    <p><%= friend.email %></p>

                    <%= f.button "Cancel", action_name: 'orders#cancel', name: "cancel-btn", value: friend.id, class: "btn btn-danger" %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="text-center col-12">You haven't invited any friends yet.</h4>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
    <div class="col">
    <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Joined friends</b>
        </div>
        <div class="card-body">
        
            <% unless @joinedFriends.nil? %>
              <% @joinedFriends.each do |friend| %>
                <div>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= "#{friend.first_name}  #{friend.last_name}" %>
                    </h5>
                    <p><%= friend.email %></p>

                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="text-center col-12">No friends have Joined yet.</h4>
            <% end %>
          
        </div>
        </div>
    </div>
  </div>
</div>
<br>
<%= link_to "Add Order Details", orders_path, {:class => "btn btn-primary active", :style => "margin-bottom:3cm; display:block;"} %>

app/views/orders/new.html.erb
<h1>Add Order</h1>

<div class="container">
  <div class="row">
    <div class="col">
      <%= form_for :newOrder, url: newOrder_url do |f| %>
        <% if @order.errors.any? %>
          <% @order.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger"><%= msg %></div>
          <% end %>    
        <% end %>
        
        <div class="form-group ">
          <%= f.label(:meal_type, {:class => 'sr-only'}) %>
          <%= f.select :meal_type, %w[Breakfast Lunch Dinner], { prompt: "Order for..."}, { class: "form-control", :style => 'margin-top: 100px; margin-bottom: 30px;'} %>
        </div>

        <div class="form-group ">
          <%= f.label(:restaurant_name, {:class => 'sr-only'}) %>
          <%= f.text_field(:restaurant_name, {:class => 'form-control', :placeholder => 'Restaurant', :style => 'margin-bottom: 30px;'}) %>
        </div>

        <div class="custom-file">
          <%= f.label(:restaurant_menu, {:class => 'custom-file-label', :for => "menu"}) %>
          <%= f.file_field(:restaurant_menu, {:id => "menu", :class => 'custom-file-input', :style => 'margin-bottom: 30px;'}) %>
        </div>

        <%= f.button 'Publish', class: 'btn btn-primary mt-5', type: 'submit' %>
      <% end %>
    </div>


  </div>
</div>
</div>

app/views/orders/show.html.erb
<h1>Order details</h1>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th>Person </th>
    <th>Item </th>
    <th>Amount </th>
    <th>Price </th>
    <th>Comment </th>
    <th>Delete </th>
  </tr>
  </thead>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.user_id %></td>
      <td><%= item.name %></td>
      <td><%= item.amount %></td>
      <td><%= item.price %></td>
      <td><%= item.comment %></td>
      <td><%= link_to "Delete", deleteItem_path(@order, item) , class: "btn btn-danger btn-sm", method: :get %></td>
    </tr>
  <% end %>
</table>
<br>

<div class="col-md-4" style="margin: 10px;">
    <a href="/orders/<%=@order.id%>/items/new">Add Item</a>
</div>