config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friends
  resources :orders
  resources :groups
  resources :groups_users

  root to: "home#index"

  
  get '/friends/:id/accept', to: 'friends#accept'
  get '/friends/:id/decline', to: 'friends#decline'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get "/orders", to: "orders#index"
  get '/orders/new', to: 'orders#new'
  post '/orders', to: 'orders#create', as: 'newOrder'
  get '/orders/:id/show', to: 'orders#show', as: 'viewOrder'
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'cancelOrder'
  get '/orders/:id/finish', to: 'orders#finish', as: 'finishOrder'

  get '/orders/invite/:id' => 'orders#inviteFriends', as: 'inviteFriends'
  post '/orders/invite/:id' => 'orders#invite', as: 'invite'
  post '/orders/inviteGroup/:id' => 'orders#inviteGroup', as: 'inviteGroup'
  delete '/orders/invite/:id' => 'orders#cancelInvitation', as: 'cancel'

  get '/orders/:id/items/new', to: 'items#new'
   
  post '/orders/:id/', to: 'items#create', as: 'newItem'
  get '/orders/:id/items/:item_id/delete', to: 'items#delete',as: 'deleteItem'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yalanotlob</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "YallaNotlob", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <%# <%= button_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %> 
        <%# <%= button_to "Sign in with Google", user_Google_omniauth_authorize_path %> 

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Groups", groups_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", orders_path,class: "nav-link" %>
        </li>
      </ul>


      <% if user_signed_in? %>
        <!--        notification part-->

        <ul class="navbar-nav md-10">
          <li class="nav-item dropdown notifications" data-behavior="notifications">
          <a class="dropdown-toggle nav-link" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="">
            <span class="fa-stack has-badge" data-behavior="notifications-link">
              <i class="far fa-bell fa-2x"></i>
            </span>
          </a>
            <ul class="dropdown-menu notifications">
              <li class="head text-light bg-dark">
                <div class="row">
                  <div class="col-lg-12 col-sm-12 col-12">
                    <span data-behavior="notifications-count">Notifications (0)</span>
                    <a href="/notifications/mark_as_read" id="notifications-read" class="float-right text-light">Mark
                      all as read</a>
                    <%#= link_to "Mark all as read", '/notifications/mark_as_read', id: "notifications-read",class: "float-right text-light", :remote => true, method: :post %>
                  </div>
                </div>
              </li>
              <ul data-behavior="notification-items">
                <!--                              <li class="notification-box">-->
                <!--                                <div class="row">-->
                <!--                                  <div class="col-lg-3 col-sm-3 col-3 text-center">-->
                <!--                                    <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">-->
                <!--                                  </div>-->
                <!--                                  <div class="col-lg-8 col-sm-8 col-8">-->
                <!--                                    <strong class="text-info">David John</strong>-->
                <!--                                    <div>-->
                <!--                                      Lorem ipsum dolor sit amet, consectetur-->
                <!--                                    </div>-->
                <!--                                    <div>-->
                <!--                                      <a href="">-->
                <!--                                        <button type="button" class="btn btn-success btn-sm">Accept</button>-->
                <!--                                      </a>-->
                <!--                                      <a href="">-->
                <!--                                        <button type="button" class="btn btn-danger btn-sm">Deny</button>-->
                <!--                                      </a>-->
                <!--                                    </div>-->
                <!--                                    <small class="text-warning">27.11.2015, 15:00</small>-->
                <!--                                  </div>-->
                <!--                                </div>-->
                <!--                              </li>-->

              </ul>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              
                <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
              
              <%= current_user.first_name %>
              <%= current_user.last_name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <!--              <a class="dropdown-item" href="#">Dashboard</a>-->
              <!--              <a class="dropdown-item" href="#">Edit Profile</a>-->
              <p class="dropdown-item"> <%= current_user.email %></p>
              <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">
                <i class="fas fa-sign-out-alt"></i>
                Log Out
              </a>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>

</html>